image: debian:testing

stages:
  - siril

variables:
  GIT_DEPTH: "1"
  INSTALL_DIR: "_install"
  INSTALL_PREFIX: "${CI_PROJECT_DIR}/${INSTALL_DIR}"
  PACMAN_CACHE:   "${CI_PROJECT_DIR}/_pacman_cache"

## GNU/Linux 64-bit CIs ##

.siril-debian/testing-base:
  stage: siril
  artifacts:
    expire_in: 1 week
    when: always
    name: "app-build-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    paths:
    - _build
    #- "${INSTALL_DIR}"
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends
        build-essential
        desktop-file-utils
        hicolor-icon-theme
        git
        intltool
        libexiv2-dev
        libgtk-3-dev
        libcfitsio-dev
        libfftw3-dev
        libgsl-dev
        libconfig-dev
        libopencv-dev
        librsvg2-dev
        libraw-dev
        libffms2-dev
        libtiff-dev
        libjpeg-dev
        libheif-dev
        libpng-dev
        libavformat-dev
        libavutil-dev
        libavcodec-dev
        libswscale-dev
        libswresample-dev
        libcurl4-gnutls-dev
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/lib/pkgconfig:${INSTALL_PREFIX}/share/pkgconfig"
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/lib/`gcc -print-multiarch`/pkgconfig/:$PKG_CONFIG_PATH"
    - export PKG_CONFIG_PATH="${INSTALL_PREFIX}/share/`gcc -print-multiarch`/pkgconfig/:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}"
    - export LD_LIBRARY_PATH="${INSTALL_PREFIX}/lib/`gcc -print-multiarch`:$LD_LIBRARY_PATH"
    - export XDG_DATA_DIRS="${INSTALL_PREFIX}/share:/usr/local/share:/usr/share"
    - export PATH="${INSTALL_PREFIX}/bin:$PATH"

siril-debian/testing-autotools:
  extends: .siril-debian/testing-base
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh
        --prefix="${INSTALL_PREFIX}"
    - make -j "$(nproc)"
    # - make check
