pixmaps = \
	b.png \
	chain.png \
	cm.png \
	curve.png \
	export.png \
	export_dark.png \
	g.png \
	grid.png \
	histo.png \
	list.png \
	mirrorx_dark.png \
	mirrorx.png \
	mirrory_dark.png \
	mirrory.png \
	monochrome.png \
	monochrome_dark.png \
	mtf.png \
	mtf_dark.png \
	neg.png \
	neg_dark.png \
	r.png \
	rotate-acw_dark.png \
	rotate-acw.png \
	rotate-cw_dark.png \
	rotate-cw.png \
	siril_logo.svg \
	siril.svg \
	starfinder.png \
	starfinder_dark.png \
	sum.png \
	sum_dark.png
