pixmaps = \
  astrometry.svg \
  astrometry_dark.svg \
	b.svg \
	cm.svg \
	curve.svg \
	export.svg \
	export_dark.svg \
	g.svg \
	grid.svg \
	histo.svg \
	list.svg \
	mirrorx_dark.svg \
	mirrorx.svg \
	mirrory_dark.svg \
	mirrory.svg \
	monochrome.svg \
	monochrome_dark.svg \
	mtf.svg \
	mtf_dark.svg \
	neg.svg \
	photometry.svg \
	photometry_dark.svg \
	r.svg \
	rotate-acw_dark.svg \
	rotate-acw.svg \
	rotate-cw_dark.svg \
	rotate-cw.svg \
	siril.svg \
	starfinder.svg \
	starfinder_dark.svg \
	sum.svg \
	sum_dark.svg \
	tilt.svg \
	tilt_dark.svg